# Generated by Django 5.1.2 on 2024-12-12 09:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_alter_contacts_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='contacts',
            name='room_name',
            field=models.TextField(blank=True, null=True),
        ),
    ]
