# Generated by Django 5.1.2 on 2024-12-13 05:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0004_contacts_room_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contacts',
            name='room_name',
        ),
    ]
