# Generated by Django 5.1.2 on 2024-12-08 08:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='chatdetail',
            old_name='user',
            new_name='sender',
        ),
    ]
