# Generated by Django 5.1.2 on 2024-12-12 09:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0002_rename_user_chatdetail_sender'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatdetail',
            name='room_name',
            field=models.TextField(blank=True, null=True),
        ),
    ]
