# Generated by Django 5.1.2 on 2024-12-13 05:49

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0005_remove_contacts_room_name'),
        ('chat', '0003_chatdetail_room_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chatdetail',
            name='contact',
        ),
        migrations.RemoveField(
            model_name='chatdetail',
            name='room_name',
        ),
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField(blank=True, null=True)),
                ('chat_type', models.CharField(choices=[('1on1', '1on1'), ('group', 'Group')], max_length=5)),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('admin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='account.userprofile')),
                ('members', models.ManyToManyField(related_name='group_members', to='account.userprofile')),
            ],
        ),
    ]
