# Generated by Django 5.1.2 on 2024-12-13 05:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0004_remove_chatdetail_contact_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatdetail',
            name='group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='chat.group'),
        ),
    ]
